[versions]
androidMinSdk = "23"
androidTargetSdk = "37"
androidCompileSdk = "37"

quickie = "1.18.1"

androidGradle = "8.13.2"
kotlin = "2.4.10"

appcompat = "1.7.1"
core = "1.17.0"

cameraX = "1.6.1"

detekt = "1.23.8"
dokka = "2.2.0"

junit = "6.1.2"
desugaring = "2.1.5"

barcodeScanning = "17.3.0"
barcodeScanningGms = "18.3.1"
coil = "3.5.0"
ezVcard = "0.12.2"
zxingCore = "3.5.4"
material = "1.14.0"

[libraries]
material = { module = "com.google.android.material:material", version.ref = "material" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxingCore" }
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-camera = { module = "androidx.camera:camera-camera2", version.ref = "cameraX" }
androidx-cameraLifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraX" }
androidx-cameraPreview = { module = "androidx.camera:camera-view", version.ref = "cameraX" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
ez-vcard = { module = "com.googlecode.ez-vcard:ez-vcard", version.ref = "ezVcard" }

mlkit-barcodeScanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }
mlkit-barcodeScanningGms = { module = "com.google.android.gms:play-services-mlkit-barcode-scanning", version.ref = "barcodeScanningGms" }

test-junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
test-junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
test-junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }

desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradle" }
android-library = { id = "com.android.library", version.ref = "androidGradle" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }